name: rest_data
description: Easily interact with REST APIs without dealing with HTTP and JSON
version: 0.2.1
author: Algonauti <info@algonauti.com>
homepage: https://www.algonauti.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  equatable: ^1.0.3
  http: ^0.12.0+4

dev_dependencies:
  test: ^1.9.4
